-d C:\Users\ooval\Desktop\ITLA\C-12\SISTEMA DIGITALES\CUATRINUEVO VIDA NUEVA\arreglandocodes\Musica\impl\gwsynthesis\Musica.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\ooval\Desktop\ITLA\C-12\SISTEMA DIGITALES\CUATRINUEVO VIDA NUEVA\arreglandocodes\Musica\src\Musica.cst
-cfg C:\Users\ooval\Desktop\ITLA\C-12\SISTEMA DIGITALES\CUATRINUEVO VIDA NUEVA\arreglandocodes\Musica\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
